### ISSUE TITLE
Additional field arguments appear as constraints

### ISSUE THREAD

**Issue by spacemanspiff2007** [mansenfranzen/autodoc_pydantic#110]
Additional keyword arguments of fields automatically appear under ``constraints`` even when they are not a constraint.

I use an additional keyword argument to specify whether the field will be created in the yaml file.
This argument is automatically documented as a constraint when it is more of a general field information.
![grafik](https://user-images.githubusercontent.com/10754716/162390543-2caa26db-3041-41c1-9a18-327f652b1a32.png)

From the [pydantic docs](https://pydantic-docs.helpmanual.io/usage/schema/#field-customization):
![grafik](https://user-images.githubusercontent.com/10754716/162390731-388c9452-1f19-4b4e-a4ed-4c1e29a0b787.png)
It seems that these kwargs are indeed intended for other purposes.
Is the documentation under `constraints` the intended behavior or is this something that is/was just out of scope?

**Comment by mansenfranzen** [comment]
@spacemanspiff2007 Thanks for opening yet another issue here ;-).

It is not intended to include additional keyword arguments passed to a pydantic `Field` under the `constraints` section in the field documentation. This edge case is not covered, yet. Thanks for reporting it! The next release will include a bugfix. This should happen rather soonish.

**Comment by mansenfranzen** [comment]
@spacemanspiff2007 This should be fixed via #111.

Before releasing the minor patch, it would be great if you could test the bug fix on your site to confirm that my test case did indeed capture the incorrect behavior which you've encountered. To do so, please install the current dev release in your doc-building-environment via `pip install git+https://github.com/mansenfranzen/autodoc_pydantic.git@v1.6.2-a.2` and rebuild your docs.

If the issue persists, please feel free to reopen this issue. Minor patch will be released next week otherwise.

**Comment by mansenfranzen** [comment]
@all-contributors please add @spacemanspiff2007 for bug and ideas

**Comment by spacemanspiff2007** [comment]
The fix works:
![grafik](https://user-images.githubusercontent.com/10754716/163310636-a957e0c0-f1e0-483d-b621-be7a06b46940.png)

---

But somehow the default value now is ``PydanticUndefined``.
The field hast a default factory so I'd argue it should not be undefined:

```
    habapp: HABAppConfig = Field(default_factory=HABAppConfig, in_file=False)
```

Is this the expected behavior or is this a new error?
