### ISSUE TITLE
WARNING: JSON schema can't be generated for 'stravalib.model.BaseEffort'

### ISSUE THREAD

**Issue by lwasser** [mansenfranzen/autodoc_pydantic#157]
hi there! 👋 i'm trying to troubleshoot a warning in our docs related to schema not rendering properly:
```
/GitHub/stravalib/docs/autodoc_pydantic.rst: WARNING: JSON schema can't be generated for 'stravalib.model.BaseEffort' because the following pydantic fields can't be serialized properly: ['activity'].
```
[You can see the build here](https://github.com/stravalib/stravalib/actions/runs/5457143994/jobs/9930844605#step:8:118)

I am also seeing some unusual JSON in the output of the documentation for some specifc classes. 
<img width="724" alt="Screen Shot 2023-07-04 at 11 44 04 AM" src="https://github.com/mansenfranzen/autodoc_pydantic/assets/7649194/2b89f309-b1d3-4b07-8db8-44814447da29">

I am not sure how to best troubleshoot this and would appreciate any guidance. Many thanks for your time!

**Comment by mansenfranzen** [comment]
Hi @lwasser,

this warning occurs because the given pydantic field `activity` of your model `stravalib.model.BaseEffort` is not serializable by pydantic. If you instantiate an instance from this class and invoke `json()` (pydantic < 2.0.0) you will receive the same error.

`autodoc_pydantic` can't really do anything about it besides handling the exception. Luckily, you can actually configure the behavior, see [here](https://autodoc-pydantic.readthedocs.io/en/stable/users/configuration.html#show-schema-json-error-strategy).

I hope that helps.

**Comment by lwasser** [comment]
@mansenfranzen thank you very much for this reply. i will dig more into it and also look into configuring the behavior as you suggest!!
many thanks for your response. i'll close this now!
