### ISSUE TITLE
Cannot use `inherited-members` directive with autosummary

### ISSUE THREAD

**Issue by alejandro-yousef** [mansenfranzen/autodoc_pydantic#183]
I would like to exclude all members from pydantic.BaseModel (e.g. copy(), schema() etc…) as described here: https://autodoc-pydantic.readthedocs.io/en/stable/users/faq.html#show-inherited-fields-validators but using **autosummary** instead.

Since it seems that the `inherited-members` directive is not supported by autosummary, is there a way to achieve this? 

Thanks for this library! :)

**Comment by mansenfranzen** [comment]
Hi @alejandro-yousef,

thanks for raising the issue here. I assume that there is no easy way to accomplish this. One approach would be to use a custom template as described [here](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#customizing-templates). Given a custom template, you can customize directive options such as `inherited-members`.

In case this is a viable solution please let me know or feel free to submit a PR to improve the documentation for other users having the same problem.

**Comment by alejandro-yousef** [comment]
Hi @mansenfranzen,

Thank you for your answer.

I'm not familiar with sphinx templates so I cannot tell if this is a viable solution yet.

Anyway would you consider adding the inherited-members directive to autosummay in a future release? or do you think it is not worth it?

**Comment by mansenfranzen** [comment]
@alejandro-yousef This change needs to be integrated in the sphinx repository. You'll need to open an issue or PR over there. This is outside of my current scope and time constraints.

**Comment by mansenfranzen** [comment]
@all-contributors please add @alejandro-yousef for ideas
