### ISSUE TITLE
Add support for root validators.

### ISSUE THREAD

**Issue by roguh** [mansenfranzen/autodoc_pydantic#20]
Hello! Thank you for the great work.

I was wondering if you were planning on adding support for documenting root validators, like you do field validators.

**Comment by mansenfranzen** [comment]
Hi roguh,

thanks for your feature request. In my opinion it's a useful enhancement and I will add it as soon as I get some spare time. It was not yet planned (simply because it was not needed yet) but it should not be too difficult to implement. Feel free to add a PR yourself if you want. Otherwise you might need to wait a week or two.

If you have some concrete ideas about how root validators should be documented, feel free to share them here. In fact, there is mainly the validator name, doc string, and optional parameters. Additionally, there should be a distinction being made between field and root validators in the documentation. Perhaps root validators should get a custom prefix like `root validator`.

**Comment by mansenfranzen** [comment]
@roguh I added support for `@root_validator`. Here is an example of how they are represented along with standard validators validating all fields `@validator("*")`: [documentation preview](https://autodoc-pydantic.readthedocs.io/en/feat_root_validators20/examples.html#asterisk-and-root-validators).

Essentially, root validators are pretty much the same as standard validators which validate all fields. Hence, they are treated the identically within the sphinx documentation. I don't think there is additional value distinguishing them in the documentation (in contrast to what I've had in mind before). 

Please feel free to comment.

**Comment by mansenfranzen** [comment]
@roguh I'm closing this issue for now with the current release v1.3.1. Feel free to reopen if you have any additional comments. Cheers.

**Comment by roguh** [comment]
Thank you so much!
