### ISSUE TITLE
Consider dropping support for sphinx version 4.X 

### ISSUE THREAD

**Issue by j-carson** [mansenfranzen/autodoc_pydantic#204]
The intersection of folks who want to use both a very old version of sphinx and the latest pydantic is probably pretty small, and it was a burden to get Sphinx 4.X working in CI on my last PR

Supporting the current Sphinx major version and "one or two back" seems sufficient, I think.

**Comment by mansenfranzen** [comment]
Hi @j-carson,

I completely get your point. It requires some work to provide the backwards comparison for older sphinx versions. You've fixed the sphinx 4 CI pipeline in your recent PR, and I very much appreciate it. However, I would like to keep sphinx 4 for now because it is still downloaded roughly 45k/day which is a bit less then 10% of overall usage ([see here](https://www.pepy.tech/projects/Sphinx?versions=7.2.6&versions=7.2.5&versions=7.2.4&versions=7.*&versions=4.*)).

I assume many devs are stuck on older sphinx versions because they are dependent on older sphinx extensions that are not compatible with recent versions of sphinx.

For now, it's less work for us to remain backwards comparison than forcing many others to upgrade or even stop using newest versions of this package. 

What do you think?

**Comment by j-carson** [comment]
Well it's less work for you, I suppose, since you got the fix handed to you in my PR, but tracking down a closed "won't fix" sphinx 4.X bug report to figure out how to fix the test automation wasn't a particularly great use of my time...

The number of requirements you want the package to meet has to be proportional to the amount of developer resources available to do the work.

**Comment by mansenfranzen** [comment]
Hi @j-carson,

Once again thanks for the time you've spent on improving and maintaining this package! Your work helps all users and developers relying on it. I've also spent several weeks of full time equivalent in initial setup and maintenance to make the user experience as good as possible for a sphinx extension. I don't get anything for this. Your work is not for me but all the users.

Especially setting up tests was rather difficult due to a lack of proper documentation and the complexity of sphinx [see here](https://github.com/sphinx-doc/sphinx/issues/7008). In contrast to this initial effort, it is well worth keeping backwards compatibility.
