### ISSUE TITLE
Config value autodoc_member_order gets ignored

### ISSUE THREAD

**Issue by ybnd** [mansenfranzen/autodoc_pydantic#21]
Looks like `autodoc_pydantic` causes `autodoc` to ignore the  `autodoc_member_order` config value
* I've got it set to "bysource"
* When building with `autodoc_pydantic` the ordering falls back to the default (alphabetical)
* Without it, everything works as expected

------------------
p.s.: Awesome plugin! I was looking for an alternative for my hacky workaround to hide pydantic model signatures and got so much more :blush:

**Comment by mansenfranzen** [comment]
Hi ybnd,

thanks for reporting the issue! Does the ordering fall back to alphabetical even for non pydantic objects or solely for pydantic models/settings which are handled by `autodoc_pydantic`. The former case would be suprising whereas the latter is likely a bug in `autodoc_pydantic` which ignores `autodoc_member_order`. 

As a side note, you may overwrite the member order specifically for pydantic models/settings as described in the [docs](https://autodoc-pydantic.readthedocs.io/en/latest/configuration.html#member-order). This should work already without waiting for bug fix ;-).

**Comment by ybnd** [comment]
I'll take a closer look at it this evening, but I think all members of modules that contain pydantic models get ordered alphabetically also.

**Comment by ybnd** [comment]
So here's an example of the issue:
* Module containing a mix of pydantic models & "regular stuff"
    * [Without autodoc-pydantic, the "bysource" order is respected](https://shapeflow.readthedocs.io/en/latest/python-library.html#module-shapeflow)
    * [With it, the order of the entire module is alphabetical](https://shapeflow.readthedocs.io/en/dev-sphinx-pydantic/python-library.html#module-shapeflow)
* Module containing no pydantic models is unaffected
    * [Without](https://shapeflow.readthedocs.io/en/latest/python-library.html#module-shapeflow.util)
    * [With](https://shapeflow.readthedocs.io/en/dev-sphinx-pydantic/python-library.html#module-shapeflow.util) 

With `autodoc_pydantic_model_member_order = "bysource"` [the ordering behaves as expected](https://shapeflow.readthedocs.io/en/dev-sphinx-pydantic-bysource/python-library.html#module-shapeflow), looks like that order option is a bit broader than intended?

**Comment by mansenfranzen** [comment]
@ybnd thanks for the detailed live examples - it helps a lot tracking down the issue here. I will come back to it soon.

**Comment by mansenfranzen** [comment]
@ybnd This was an interesting bug to track down. As you've guessed, autodoc pydantic did in fact modify the member order of other auto-documenters. However, this occurred because the actual `options` attribute (resembling things like `members` or `member-order`) is shared among multiple auto-documenters which in fact seems rather strange to me. For example, if you modify the options for one documenter, you may change it for another one, too. The solution was rather simple by creating a separate copy of each `options` instance for every auto-documenter in `autodoc_pydantic` (see [here](https://github.com/mansenfranzen/autodoc_pydantic/pull/24/files#diff-22d438c89efa8841f948cae9b86a6db97fe91a561d0dffe3a26f769c51df1b40R143))

I added a test case to resemble the observed bug (see [here](https://github.com/mansenfranzen/autodoc_pydantic/pull/24/files#diff-6b9e49f428073c3fd3a9d2a1b8f02469a2df655f9b22b795c41950ae89f5f2f0R1) and [here](https://github.com/mansenfranzen/autodoc_pydantic/pull/24/files#diff-73a52216dff9ee38057385009e82ea2a687989a7cf2f27e8e55414da44bf2148R145)).

Before merging the related PR, it would be great if you could test the bug fix on your site to confirm that my test case did indeed capture the incorrect behavior which you've encountered. To do so, please install the current dev release in your doc-building-environment via `pip install git+git://github.com/mansenfranzen/autodoc_pydantic.git@v1.3.1-a.1` and rebuild your docs.

Thanks!

**Comment by ybnd** [comment]
[Looks like everything works as it should](https://shapeflow.readthedocs.io/en/latest/python-library.html#module-shapeflow) 👍 
* With the release ↑
* Removed `autodoc_pydantic_model_member_order = "bysource"` option
* Module member order is `bysource` and pydantic model order is alphabetic

**Comment by mansenfranzen** [comment]
Great, thanks for testing! I hope to get the release done until next week.
