### ISSUE TITLE
Autodoc Pydantic not working with Sphinx 7.3

### ISSUE THREAD

**Issue by Carson-Shaar** [mansenfranzen/autodoc_pydantic#274]
Our doc builds have not been working since 7.3 of Sphinx was released and downgrading 7.2.6 fixed my issue.  Below are the error logs and the part of the rst file that broke it:

[sphinx-err-mz06c_bc.log](https://github.com/mansenfranzen/autodoc_pydantic/files/15099919/sphinx-err-mz06c_bc.log)

.. autopydantic_model:: zero_true.Layout 
    :model-show-field-summary: false
    :model-show-validator-summary: false

**Comment by mansenfranzen** [comment]
Thanks for raising the issue. I will need to investigate in more detail. 

Just to make sure, you are installing autodoc_pydantic from pypi and not from source via GitHub, right?

**Comment by mansenfranzen** [comment]
This is an odd error. The actual exception is not raised by `autodoc_pydantic` but by `sphinx`. In fact, for the given piece of code: https://github.com/mansenfranzen/autodoc_pydantic/blob/b9b4e2dea2b380c9ec4289068bea07b06fcf50e3/sphinxcontrib/autodoc_pydantic/directives/options/composites.py#L227-L231 

`autodoc_pydantic` wants to iterate through all Sphinx environment configurations and delegates this to the following Sphinx internals:

https://github.com/sphinx-doc/sphinx/blob/de4ac2fbdebae529a973910e96794645158f0401/sphinx/config.py#L431-L433

It seems as if your sphinx environment has some configuration value that does not have the `rebuild` attribute defined. I don't know which configuration exactly causes the error. Likely this is not caused by `autodoc_pydantic` directly. 

If your repository is public, I could debug myself. If not, you will need to debug it yourself. If using a debugger feels intimidating, you can just add a print to show the name of the config. Moreover, it would be useful if you could share your `conf.py`.

**Comment by ITProKyle** [comment]
I'm seeing the same issue. Disabling this extension results in by documentation building successfully. Unfortuniatly, my project is private so I can't provide an example but I have some additional info.

With the last location in the traceback being the following:

```
.../sphinx/config.py", line 433, in __iter__
    yield ConfigValue(name, getattr(self, name), opt.rebuild)
```

I inserted a quick and dirty print statement to see what config value was triggering the error.

```python
    def __iter__(self) -> Iterator[ConfigValue]:
        for name, opt in self._options.items():
            print(f"{name = }  |  {opt = }")
            yield ConfigValue(name, getattr(self, name), opt.rebuild)
```

The output received just before the error is `name = 'html_permalinks_icon'  |  opt = ('#', 'html', ())`.
I do not have `html_permalinks_icon` defined in my `conf.py` so it is being triggered by the default value ([docs](https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output)).

Doing a bit more digging, sphinx 7.3.2 patched a bad interaction with furo (which i am using) involving a tuple so this may be a continuation of that.

Versions I'm currently using:

```yaml
autodoc_pydantic: 2.1.0
furo: 2024.1.29
sphinx: 7.3.7
```

**Comment by Carson-Shaar** [comment]
@mansenfranzen my project is public: https://github.com/Zero-True/zero-true.

The issue occurred both locally (Windows) and in a GHA running on Ubuntu.  Locally it was Python 3.11 and GHA is 3.9 I believe.

**Comment by mansenfranzen** [comment]
@all-contributors please add @Carson-Shaar for bug

**Comment by mansenfranzen** [comment]
@all-contributors please add @ITProKyle for bug

**Comment by mansenfranzen** [comment]
@all-contributors please add @bruno-f-cruz for bug
