### ISSUE TITLE
Config subclass is shown when explicitly set otherwise

### ISSUE THREAD

**Issue by Ecaloota** [mansenfranzen/autodoc_pydantic#291]
Given the following relevant `conf.py` options:

```python3
autodoc_pydantic_model_show_config_summary = False
autodoc_pydantic_model_show_config_member = False
autodoc_pydantic_config_members = False
```

And a Pydantic model such as the following:

```python3
class MyClass(BaseModel):
    job: str
    
    class Config:
        foo = 'bar'
```

And a rst file containing an `.. automodule::` directive pointing the module which contains that model, I obtain rendered output which contains an empty field containing `class Config`. Also, the docstring for the Config subclass is rendered if present, and excluded if given an explicit `:meta private:` directive.

![screencap](https://github.com/mansenfranzen/autodoc_pydantic/assets/29943815/384e30a9-fed5-4312-8cd7-25ce3b2a7843)

I would expect that at least the `autodoc_pydantic_model_show_config_member` might prevent the Config subclass from being rendered -- am I missing something?

Using version 2.2.0

**Comment by mansenfranzen** [comment]
Hi @Ecaloota,

thanks for raising this issue here!

I think you've might have mixed up the different versions of `autodoc_pydantic` regarding the documention.

`autodoc_pydantic_model_show_config_member` does only exist in `v1` (see [here](https://autodoc-pydantic.readthedocs.io/en/v1.9.0/users/configuration.html#show-config-member)) but was removed in `v2` (see [here](https://autodoc-pydantic.readthedocs.io/en/v2.2.0/users/configuration.html#model)). In `v2`, you can hide model configs via [`autodoc_pydantic_model_show_config_summary`](https://autodoc-pydantic.readthedocs.io/en/v2.2.0/users/configuration.html#show-config-summary).

Please be aware, the nested `Config` class is deprecated in pydantic v2. Instead, you should use `model_config`.

I hope this helps.

Feel free to reopen this issue.

**Comment by mansenfranzen** [comment]
@allcontributors please add @Ecaloota for question

**Comment by Ecaloota** [comment]
Thanks for clarifying!
