### ISSUE TITLE
Docstring of base class' `__init__` included

### ISSUE THREAD

**Issue by lilyminium** [mansenfranzen/autodoc_pydantic#58]
Thanks for creating this package, @mansenfranzen -- it's the missing link between the self-documenting objects of Pydantic and, well, actual documentation!

However, I'm not sure I've set it up correctly. Might you know why the class docstrings I'm getting have the Pydantic BaseModel docstring attached? e.g. here: https://psiresp.readthedocs.io/en/latest/_autosummary/psiresp.job.Job.html#psiresp.job.Job

If you look at the source, it includes the first part only:

https://psiresp.readthedocs.io/en/latest/_modules/psiresp/job.html#Job

Is it because I'm using `autosummary` instead of `autopydantic_model` or similar?

**Comment by mansenfranzen** [comment]
Thanks for reporting this. It is indeed an odd behaviour. 

It has nothing to do with `autosummary` because this simply generates the `autopydantic_model` directive. Instead, I believe the reason is located in your `conf.py` which sets `autoclass_content = 'both'`. This tells sphinx autodoc to concatenate both the class doc string and its `__init__` doc string in the class' documentation (see [here](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration)). The `psiresp.job.Job` class inherits its `__init__` from `pydantic.BaseModel` hence you see the doc string from pydantic's `BaseModel`. Could you please check if it disappears if you set `autoclass_content = 'class'`?

I guess you might not be the first or the last who stumbles across this. Describing this could be a good candidate for the documentation's FAQ section. If you want feel free to add a PR. Otherwise I can do it.

**Comment by lilyminium** [comment]
That did the trick, thank you @mansenfranzen! (https://psiresp--37.org.readthedocs.build/en/37/_autosummary/psiresp.job.Job.html#psiresp.job.Job)

I'm happy to put up a PR today.
