### ISSUE TITLE
Styling lost with Jupyter Book

### ISSUE THREAD

**Issue by StigKorsnes** [mansenfranzen/autodoc_pydantic#77]
Hello Sir,
To be honest, I'm not sure whether or not this question belong in [Jupyter-Book](https://github.com/executablebooks/jupyter-book/issues#:~:text=executablebooks,jupyter%2Dbook) or here. I`m facing an issue, and in a hurry to solve it. I'm using Jupyter-Book to document a library for a client. I have some bakground material/examples which I have produced with markdown/python-code (.md and ipynb), and I have the "API reference" in the last chapter using an rst-file. All works fine, except when I tried using autodoc_pydantic.  All pydantic models loose their styling. I.e if I have a module containing say a regular Exception, and another class derived from a Pydantic BaseModel, the Exception will turn out like your examples, but all pydantic models look pretty wierd.  They get idented properly, and I can toogle JSON schema on/off in configs, but all styling such as the blue background on the signature is lost. Have tried both automodule and autopydantic_ with same results. Any idea what is going on?
Great project, btw :)

Very best,
Stig

**Comment by mansenfranzen** [comment]
Hi @StigKorsnes,

sorry for letting you wait -  I was busy otherwise. 

Your issue seems to be related to how custom autodoc extensions automatically provide a new css class with the same name as `objtype`/`directivetype`. Without `autodoc_pydantic`, documenting python classes get the css class named `class`. Here is an extraction of the generated autodoc HTML source code without using `autodoc_pydantic`:

```html
<dl class="py class">
```

When enabling `autodoc_pydantic`, the above HTML changes to:

```html
<dl class="py pydantic_model">
```

As far as I know there is no easy way to change this behavior. It would be best to have both classes available like:

```html
<dl class="py class pydantic_model">
```

The same holds for pydantic fields, settings and so on:

- pydantic_model -> class
- pydantic_settings -> class
- pydantic_field -> attribute
- pydantic_validator -> method
- pydantic_config -> class

Hence, the issue lies in replacing css class `class` with `pydantic_model`.

How this affects your theming is dependent on whether your theme makes use of the original css classes (`class`, `attribute`, `method`) or not. For example, the standard read-the-docs theme has no issue with it. However, your theme obviously makes use of it. 

One hackish work around is to simply add all styles that are given under `class`, `attribute`, `method` to the corresponding `autodoc_pydantic` css classes as show above. This should work.

It would be great if you could test this approach. If it works, it would be worth adding it to the users FAQ section as long as I can't provide a proper fix codewise.

**Comment by mansenfranzen** [comment]
Hi @StigKorsnes,

sorry for letting you wait -  I was busy otherwise. 

Your issue seems to be related to how custom autodoc extensions automatically provide a new css class with the same name as `objtype`/`directivetype`. Without `autodoc_pydantic`, documenting python classes get the css class named `class`. Here is an extraction of the generated autodoc HTML source code without using `autodoc_pydantic`:

```html
<dl class="py class">
```

When enabling `autodoc_pydantic`, the above HTML changes to:

```html
<dl class="py pydantic_model">
```

As far as I know there is no easy way to change this behavior. It would be best to have both classes available like:

```html
<dl class="py class pydantic_model">
```

The same holds for pydantic fields, settings and so on:

- pydantic_model -> class
- pydantic_settings -> class
- pydantic_field -> attribute
- pydantic_validator -> method
- pydantic_config -> class

Hence, the issue lies in replacing css class `class` with `pydantic_model`.

How this affects your theming is dependent on whether your theme makes use of the original css classes (`class`, `attribute`, `method`) or not. For example, the standard read-the-docs theme has no issue with it. However, your theme obviously makes use of it. 

One hackish work around is to simply add all styles that are given under `class`, `attribute`, `method` to the corresponding `autodoc_pydantic` css classes as show above. This should work.

It would be great if you could test this approach. If it works, it would be worth adding it to the users FAQ section as long as I can't provide a proper fix codewise.

**Comment by mansenfranzen** [comment]
Hi @StigKorsnes,

sorry for letting you wait -  I was busy otherwise. 

Your issue seems to be related to how custom autodoc extensions automatically provide a new css class with the same name as `objtype`/`directivetype`. Without `autodoc_pydantic`, documenting python classes get the css class named `class`. Here is an extraction of the generated autodoc HTML source code without using `autodoc_pydantic`:

```html
<dl class="py class">
```

When enabling `autodoc_pydantic`, the above HTML changes to:

```html
<dl class="py pydantic_model">
```

As far as I know there is no easy way to change this behavior. It would be best to have both classes available like:

```html
<dl class="py class pydantic_model">
```

The same holds for pydantic fields, settings and so on:

- pydantic_model -> class
- pydantic_settings -> class
- pydantic_field -> attribute
- pydantic_validator -> method
- pydantic_config -> class

Hence, the issue lies in replacing css class `class` with `pydantic_model`.

How this affects your theming is dependent on whether your theme makes use of the original css classes (`class`, `attribute`, `method`) or not. For example, the standard read-the-docs theme has no issue with it. However, your theme obviously makes use of it. 

One hackish work around is to simply add all styles that are given under `class`, `attribute`, `method` to the corresponding `autodoc_pydantic` css classes as show above. This should work.

It would be great if you could test this approach. If it works, it would be worth adding it to the users FAQ section as long as I can't provide a proper fix codewise.

**Comment by StigKorsnes** [comment]
Hi @mansenfranzen 
Thank you very much for your response. I quickly realized that this issue had nothing to do with your package, as I encountered the same issue with sphinx-toolbox  and enum_tools. (for named tuples and enums, which also lacks a bit out-of-the-box).

My experience and understanding of CSS is close to zero, so do not know how to go about to fix the build-step of my documentation. However, I was able to open the dev tools and throw a "class" in there to witness magic happen :) (py class pydantic_model).  I guess I will have "up" my skillset in order to implement any sort of hack. Had a colleague test it out with RTD and sphinx, where everything looks nice, as you have already mentioned. 

Jupyter-book uses a custom book-theme, and I guess since this and other contributed extensions work in other themes, that the issue lies here. Posted an issue [here](https://github.com/executablebooks/jupyter-book/issues/1563#issue-1073186495). Since this issue applies not only to your package, but all other contributed extensions with similar goals, I think it does deserve a bit more attention than currently given. (0 replies). Feel free to post a short comment, any support is appreciated.

Thank you very much for your reply!

**Comment by mansenfranzen** [comment]
@StigKorsnes Thanks for the response - I'm glad it seemed to have helped you. Just to clarify so I don't misunderstand you: When you add `class` then the styling is correct again?

More importantly, your issue gave me the idea to use sphinx [events](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-object-description-transform) to add the missing css class `class` automatically. This will be in fact a useful addition to the package and perhaps for other packages, too.

I will let you know about the new feature in the next release.

**Comment by mansenfranzen** [comment]
@all-contributors please add @StigKorsnes for bug and ideas

**Comment by mansenfranzen** [comment]
The current release v1.6.0 adds the relevant fallback classes by default. Therefore, the newest version of **autodoc_pydantic** should work fine with jupyter-book theme out of the box, now. It would be great, if you could test this once again to confirm that I'm not mistaken. 

There is a new [FAQ section](https://autodoc-pydantic.readthedocs.io/en/stable/users/faq.html#broken-layout-for-aut) in the updated documentation describing your issue. 

Feel free to reopen or comment. Thanks once again for reporting the issue.

**Comment by StigKorsnes** [comment]
@mansenfranzen 
Updated to 1.6.0, and everything looks good!

**autodoc-pydantic 1.5.1 :**

![Inkedautodoc_pydantic_before_LI](https://user-images.githubusercontent.com/10085536/148035314-bb71c7ca-9f45-430c-995b-ff1bd1c8d002.jpg)

**autodoc-pydantic 1.6.0 :**

![Inkedautodoc_pydantic_after_LI](https://user-images.githubusercontent.com/10085536/148035586-7cad75e2-cc44-4e40-8b98-fddd77e66a9f.jpg)

Thank you very much for this. Would you recomend your implemented solution to other packages such as sphinx-toolbox and enum_tools?

**Comment by mansenfranzen** [comment]
Thanks for the visual confirmation - looks good :-).

I believe that this feature is also relevant for other sphinx autodoc extensions. Thanks for linking this PR to the related packages.
