### ISSUE TITLE
Links behave unexpectedly in the Example - ExampleSettings on the readthedocs

### ISSUE THREAD

**Issue by jgunstone** [mansenfranzen/autodoc_pydantic#96]
this looks like a great package! 

I was just looking at the documentation and when you hit "source":
![image](https://user-images.githubusercontent.com/21370980/152397316-1bd20dc0-685f-4204-aec4-bcaefebcce4f.png)

it behaves as expected taking you to the source code... but then when you hit the equivalent "docs" link to go back:
![image](https://user-images.githubusercontent.com/21370980/152397537-bae87728-7207-4ed3-80d5-56fecceed908.png)

it takes you to the "Usage" section rather than the "Examples" section you came from: 
![image](https://user-images.githubusercontent.com/21370980/152397676-b4bdc252-952e-434c-8ee8-f6accf6f873e.png)

otherwise looks great - can't wait to use it in my next package

**Comment by mansenfranzen** [comment]
@jgunstone Thanks for reporting this. It is indeed a weird behavior. Perhaps that's even a bug in sphinx `sphinx.ext.viewcode`. I will come back to it soonish.

**Comment by mansenfranzen** [comment]
@jgunstone This bug is fixed with the upcoming release which will be released soonish. You can see the update docs already [here](https://autodoc-pydantic.readthedocs.io/en/v1.6.2-a.1/users/examples.html).

The issue arose because the same source code was auto-documented multiple times by different doc pages and `sphinx.ext.viewcode` can only use a single back-reference to the doc pages.

**Comment by mansenfranzen** [comment]
@all-contributors please add @jgunstone for bug
